# feeder
feeder: st_relation.feeder.Feeder
test_feeder_args:
  mode: test
  window_size: 300
  data_path: ./data/NTU-RGB-D/xview/val_data.npy
  label_path: ./data/NTU-RGB-D/xview/val_label.pkl

# model
model: st_relation.net.ST_RELATION
model_args:
  num_class: 60
  channel: 28
  window_size: 300
  num_point: 25
  num_person: 2
  graph: st_relation.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  use_data_bn: True

# test 
phase: test
device: 0
test_batch_size: 64
weights: ./model/ntuxview-st_relation.pt